{% set name = "git-remote-s3" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/git_remote_s3-{{ version }}.tar.gz
  sha256: 18a42b269a0ea9dfe49f1d23dc61dfe0ad497efea11bcc80e75be250fc156abf

build:
  entry_points:
    - git-remote-s3 = git_remote_s3.remote:main
    - git-lfs-s3 = git_remote_s3.lfs:main
    - git-s3 = git_remote_s3.manage:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }}
    - boto3 >=1.34.155,<2.0.0

test:
  imports:
    - git_remote_s3
  commands:
    - pip check
    # These don't have working --help options yet
    # - git-remote-s3 --help
    # - git-lfs-s3 --help
    - git-s3 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/awslabs/git-remote-s3
  summary: A git remote helper for Amazon S3
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE

extra:
  recipe-maintainers:
    - thewchan
