schema_version: 1

context:
  name: git-remote-s3
  version: 0.2.4
  python_min: 3.10

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/git_remote_s3-${{ version }}.tar.gz
  sha256: dd21474901f57679b21d3746f4e72d7d37ddccf3c67ef231fac7756ce3ee4407

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - git-remote-s3 = git_remote_s3.remote:main
      - git-lfs-s3 = git_remote_s3.lfs:main
      - git-s3 = git_remote_s3.manage:main

requirements:
  host:
    - python ${{ python_min }}.*
    - poetry-core
    - pip
  run:
    - python >=${{ python_min }}
    - boto3 >=1.34.155,<2.0.0

tests:
  - python:
      imports:
        - git_remote_s3
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - git-s3 --help

about:
  summary: A git remote helper for Amazon S3
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  homepage: https://github.com/awslabs/git-remote-s3

extra:
  recipe-maintainers:
    - thewchan
